name: Build and Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Get project name
        id: get_project_name
        run: echo "name=$(basename RadioM3U/RadioM3U.csproj .csproj)" >> $GITHUB_OUTPUT

      - name: Clear NuGet cache
        run: dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore RadioM3U/RadioM3U.csproj

      - name: Build
        run: dotnet build RadioM3U/RadioM3U.csproj --configuration Release --no-restore

      - name: Package plugin
        run: |
          mkdir -p "dist/${{ steps.get_project_name.outputs.name }}"
          cp "RadioM3U/bin/Release/net8.0/${{ steps.get_project_name.outputs.name }}.dll" "dist/${{ steps.get_project_name.outputs.name }}/"
          cp "RadioM3U/bin/Release/net8.0/${{ steps.get_project_name.outputs.name }}.pdb" "dist/${{ steps.get_project_name.outputs.name }}/"
          cp manifest.json "dist/${{ steps.get_project_name.outputs.name }}/"
          cd dist
          zip -r "${{ steps.get_project_name.outputs.name }}_${{ github.ref_name }}.zip" "${{ steps.get_project_name.outputs.name }}"
          cd ..
          sha256sum "dist/${{ steps.get_project_name.outputs.name }}_${{ github.ref_name }}.zip" > "dist/${{ steps.get_project_name.outputs.name }}_${{ github.ref_name }}.zip.sha256sum"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/${{ steps.get_project_name.outputs.name }}_${{ github.ref_name }}.zip
            dist/${{ steps.get_project_name.outputs.name }}_${{ github.ref_name }}.zip.sha256sum